### ISSUE TITLE
Some bytes in OP Talk was not decompiled correctly.

### ISSUE THREAD

**Issue by illidan2004** [TwnKey/SenScriptsDecompiler#1]
Thank you for your decompiler and compiler.  I use it to decompile the original sen4 scena script and modify some translation texts. When I decompiled it and only modified the dialog content, then recompiled for game. I found some error text display in dialog. So I think maybe I found a problem.

See this op code in v3010.dat, when byte 11 91 98 00 00 -> 17 39057 is for voice id, following #E[3333333333333333333333336] in the text which is special command for displaying dialog.  Then  # (23) is decompiled as unknown character in the table, and it becomes EF BF BD when it is compiled. Which cause the game display E[3333333333333333333333336] as part of text.

![image](https://user-images.githubusercontent.com/14799924/116347354-a2dfe700-a81e-11eb-90b9-1260676c04e0.png)

**Comment by TwnKey** [comment]
Thank you for reporting this bug and sorry for the delay, I didnt get notified. I will check that as soon as possible.

**Comment by illidan2004** [comment]
Thank you for fixing this problem.  I have another advice, I think you can compile "01" (which means text to next row) in the dialog as an "\n" or "\1" in an Excel cell, so we can copy/paste or edit text more easily.
